default: &default
 adapter: mysql2
 pool: 5
 timeout: 5000
 host: localhost
 database: ebook_pavilion
 username: root
 password: 123456

development:
 <<: *default

test:
 <<: *default

production:
  <<: *default
